#! /usr/bin/python37
"""
Author: Wytze Gelderloos
29-7-2019
Calculating Protein mass script.
Calculates the protein mass for a given protein sequence.
Uses regex to parse the proteins and mass into a dictionary.
Then iterates over the protein sequence and prints its mass rounded to
three decimals.
"""

import regex as re
string = """A   71.03711
C   103.00919
D   115.02694
E   129.04259
F   147.06841
G   57.02146
H   137.05891
I   113.08406
K   128.09496
L   113.08406
M   131.04049
N   114.04293
P   97.05276
Q   128.05858
R   156.10111
S   87.03203
T   101.04768
V   99.06841
W   186.07931
Y   163.06333 
"""
letters = re.findall("[A-Za-z]", string)
numbers = re.findall("(?:\s)(\d*|.*)(?:\n)", string)
numbers2 =[]
## strip spaces from numbers and intitialize as a float
for num in numbers:
    numbers2.append(float(num.strip("  ")))
## making the dictionary with key: protein, value: mass
dictie={}
for i in range(len(numbers2)):
    dictie[letters[i]] = numbers2[i]


string = "SCGDTAEVYMLHIMTPKATNEVCFWYQSQPHWCQFLVMMPKMTLPIHRGIDHKLSNRINTRCKVDEEIDVMDQIDLNIIHDQAENYEMPHYCVYPICNSTRVGNNSKKHLKCWIRDGVDYSSIQYINRQRIEWNYCYGKVQYERDGYYFFKKRRNFCPRRFHTGTWNQQWYITRIVCHNTIHSDHRPAECAGCRLVSPPKGMKWVKYLHMCKIDAAQERLKCYAPMGWESILWLGGDLHLYGQSCWFKEQSWYYQVAADIKWPEGDCNLHMKLPVSYMFRVSATSKHMQWPCWEAVNYPQRSYHVDSCTCHEIRDDPCWGLFARIPETTRVYSRWTMPRPCQHFRTFSSHDETIPYCIFLFSPFHFHPPRNIPPHTDMETDCIGNPHHLHMRYYRMQRTWPRYAQEAHMHVSILSLWPLTVAQRQSCDPIHNWFSIVNCDRTETGEKQEDPHNPELRGWPRSHYDEWVGGMDWHAHYIKYVAPPYGVQDESSPATSTWFFNLPLESTLHFSWKCYHWEAGTIDMQWTNIHWHNCHENIEIKRMQEYTNNDAYMPYYVVDLADGSDRVTMVLPKRWCMEIHYVHNHRALQSSHHIKDPWEVTPPNFCGGDILLIIQMTYGKQQWSWLHEAQQKPMHPTAGDSVELWGAGICWDEMNDAHTYFGSMMYVVWLLHMPGERMPWLNYHNTTQQSHACYELKNDCGPLPTDSVMSKPQGHVACKQIQYLSGWWTLVRGMKCYQPASCRPIFAQKSAQHRPQCYGLSMKCKDVIMYAQARQEECPHCICNMEWAMYCRGLQMKQPFGGDVYQAACDFEMGWGIDNKEQWFTGAGPYDFQIFGALADWTKQCSPCIIRIAELFTVIHS"
score = 0 
for stri  in string:
    score += dictie[stri]



print(round(score,3))
