#! /usr/bin/python37
"""
Author: Wytze Gelderloos
Date: 29-7-2019
inferring RNA from protein.
This script infers the total number of different RNA string which could
 produce the protein sequence provided modulo 1 million.

"""
table2 = {
    "F":["UUU","UUC"],
    "L":["UUA","UUG","CUU","CUC","CUA","CUG"],
    "S":["UCU","UCC","UCA","UCG","AGU","AGC"],
    "Y":["UAU","UAC"],
    "Stop":["UAA","UAG","UGA"],
    "C":["UGU","UGC"],
    "W":["UGG"],
    "P":["CCU","CCC","CCA","CCG"],
    "H":["CAU","CAC"],
    "Q":["CAA","CAG"],
    "R":["CGU","CGC","CGA","CGG","AGA","AGG"],
    "I":["AUU","AUC","AUA"],
    "M":["AUG"],
    "T":["ACU","ACC","ACA","ACG"],
    "N":["AAU","AAC"],
    "K":["AAA","AAG"],
    "V":["GUU","GUC","GUA","GUG"],
    "A":["GCU","GCC","GCA","GCG"],
    "D":["GAU","GAC"],
    "E":["GAA","GAG"],
    "G":["GGU","GGC","GGA","GGG"],
}




proteinstring = "MYPPHDKVEWWMHGPHTQMKQQPEALPDDCPNNCMQAYLALNHTKVIVLMDECQGVVYGSKPRRFNFHGNGETWKPLAQCCLNHGNKLEHYHADCSIAPAEFAIAWMYVIAIEWRHCIFNMASPRLPINYYDCRLKLEDWTNPQKWPHMVTFRYKNPAESHECQLNMLFFAFVKAVTNVNQAEARPWWQMHKQTKFILWLTAFLIWQILPMVSIQPQLSHQYAICICYMQNMVSCQRSSNVWAPLLHQRVPKYESVNLIHMGSGGRVECKPHCEHYGGSAPVTYSFHPPFGFMPCVYTPCYRRPWDSWPNALERVLCYWLFLIRLLEFMQFSDAANFKSVWIAKNPDQTNKDTEMKMAPQPEMQDTFLHCCEIWEWMYNTPYRGRCENTCMCVDVHFNIIDCAFVVFGEWVNWYGWPNLRTDYEYMWASSETIQQTWCSGEVWDWDDSNCLSEHCVLMPGGYDEFNQFRHSYDLQQNVQLENRVFLTGFTEWNVGMCAHPWNASMGFTVCRPRPMWTIQMSAMGYSKMGMSKHEEAAAWCGTKLLMMWWGTKYWDWNNHQYVRHIDQVNSVHGMQQVNYPPIAEHVQFHCYKDVLRPQGNVGGQELQAHKVLVCWWPLHHARSDWVSMSFCYLPFAHLPTLPVPGRSDTDAPMHIEPAWPENRILNFTHSWRSRWCACDYDAFWMKDWKPRICSVSPCHWDPYACNFRDRPEPIMYQVCHQSRMAMLFLNMRMPNMVMVKRCMYRIKFDHTQSVKAMARKDHFPNYPRWQNDGCATWSHPFRSIKGAWNQTCKGIWCKPWVTTWCGPACFGVKSCDSNCDKYFWLPYNCFGFNRGWPYFHHRATEFKHEYNGGQSVFVHMPQMLDHINLPNRHVWNKLYGPPYELQDACNVCRPCAFVREKRMVWPDCLQGLIQHFKMAHTALRWDKKENQISGDCDQFTGRTLSDHWGCNHQHRRKEVEWFHFPWGTNTFNVREYSRNVFHDFSWPPDVEDERNRSG"


pos_list=[]

for let in proteinstring:
    pos_list.append(len(table2[let]))


print(pos_list)

result =  1
for i in pos_list:
    result = result * i

print((result*3) % 1000000)
